### ISSUE TITLE
Screenshots not being taken.  

### ISSUE THREAD

**Issue by adamsrobw** [mlison/protractor-jasmine2-screenshot-reporter#10]
Hello. 

This creates a folder for me. and puts the html report in there.

but there are no .png files in the folder.  

the report has hyperlinks that go to nowhere. 

there are no errors in the console. 

any ideas?

var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

```
jasmine.getEnv().addReporter(
  new HtmlScreenshotReporter({
    dest: 'target/screenshots',
    filename: 'my-report.html'
  })
);
```

**Comment by chazzlabs** [comment]
@adamsrobw What versions of Protractor and Jasmine are you using?  I'm using Protractor 2 and Jasmine 2, but I'm not seeing any results at all; not even a report.html file is being created after my tests.

This is my config:

```
jasmine.getEnv().addReporter(new HtmlScreenshotReporter({
                dest: 'target/protractor/screenshots',
                filename: 'my-report.html',
                captureOnlyFailedSpecs: true
            }));
```

**Comment by adamsrobw** [comment]
i have the same as you.

its wierd i just looked and i had a 131331235y123y123.png  but no report.  

ive spent all day trying to to figure out how to print screenshots on test failures in jasmine 2.0 and i havent been able to do it

**Comment by chazzlabs** [comment]
I rolled back to 0.1.3 to see if there was any difference, and I noticed a couple things:
- 0.1.3
  - My 'dest' directory is not created if it does not exist.
  - If the 'dest' directory already exists, a report.html file is created for each browser, but each file is completely empty.
- 0.1.4
  - My 'dest' directory is not created if it does not exist.
  - If the 'dest' directory already exists, the report.html files are still not created at all.

I'm guessing this is an issue with updating to Protractor 2.  My colleague who started this project was using Protractor 1 and said he didn't have any issues getting our reporters working with our integration tests.  The only change I've made since then is updating to Protractor 2.

**Comment by adamsrobw** [comment]
so i found out that if we connect to our selenium grid,  it works fine.   if i try to run a local selenium server . it doesnt work.

**Comment by chazzlabs** [comment]
What version of Selenium is running on each environment?

**Comment by adamsrobw** [comment]
running locally with selenium-server-standalone-2.45.0.jar  was not working.  im not sure what our selenium grid is using.

**Comment by EMCP** [comment]
I too am not seeing any output, unsure how to proceed.

**Comment by giri-sh** [comment]
Is there an update on this issue? I am facing the same issue too. My whole test suite stops in between and throws an error stating "cannot take screenshot" whenever there is a failure of a spec.

**Comment by donaldpipowitch** [comment]
Same problem here.

**Comment by NeverwinterMoon** [comment]
I am getting this problem when running Protractor using multiple instances only. I run 5 instances at once, and some of the suits are always missing screenshots for the first few tests. They are referenced in report.html, but files are nowhere to be found. Running only one instance at a time is fine, but falling back on this in my case is not acceptable for speed reasons.

**Comment by NeverwinterMoon** [comment]
OK, I did a more through investigation and what I wrote earlier is a bit off.

If I have 5 specs and 5 instances (Protractor's maxInstances property), everything works grand. The problem arises all the time when there are more specs than there are instances. Say, 5 instances and 6 specs. In this case, whenever one of 5 instances finishes and the 6th one takes it place, _all_ screenshots made to this point are erased.

**Comment by EMCP** [comment]
I notice if I minimize the browser window, screenshots also fail.

**Comment by NeverwinterMoon** [comment]
I was able to solve the problem we were having by forking the project and taking a few quick hacks at it. Basically, now every suite will have its own folder which will contain all the screenshots, and the report.html will have a prefix of suite name and will be written just outside the folder. Note that we use the spec name in camel case as the top describe of every suite so it works well with that setup, so it looks like this:

```
shuttle
backToDesktop
shuttle_report.html
backToDesktop_report.html
```

This is the fork: https://github.com/NeverwinterMoon/protractor-jasmine2-screenshot-reporter

This is how it looks like in package.json:

```
"protractor-jasmine2-screenshot-reporter": "NeverwinterMoon/protractor-jasmine2-screenshot-reporter#0.2.2"
```

If you don't provide version (ex: #0.2.2), it will take latest changes.

It was a quick and dirty job but it seems to work fine. If this fork helps anyone, I might be able to improve a bit on it.

**Comment by richtera** [comment]
This fork however seems to have some other problems. It somehow has a builtin path calculation which causes the image not to be saved. I see it taking the screenshot now (i.e. it pulls the browser front) but the image does not end up on disk. Also my report now contains the name of the item which I don't want but if the folders at least got generated this would be usable.

**Comment by richtera** [comment]
Ah, the fork is incompatible with the following settings:

``` javascript
  ignoreSkippedSpecs: true,
  captureOnlyFailedSpecs: true,
  reportOnlyFailedSpecs: false
```

Unfortunately I was unable to post the issues to the fork directly, sorry to convolute things, but the issues button does not show up on the fork.

**Comment by NeverwinterMoon** [comment]
As I mentioned earlier, the fork was made only to quickly fix the problem we had in the way we needed - we wanted screenshots grouped by suite name (the name in our case is the topmost describe). This name is used in the path to create a folder and allow that grouping. Still, I am wondering, why the image is not saved in your case as it works really well for us even now.

If you could provide more details about your set up, I would gladly try to address the problem, if possible.

I enabled issue reporting on the fork, try using it now.

**Comment by richtera** [comment]
My problem is specifically that the last test will not save the screen shot if it fails.
This is because jasmine has async support but not for jasmineDone or specDone. Which means that the screenshot has to either be patched into the Spec.execute and then jasmineDone will either save or not save the screenshot or there would need to be some other way to delay finalization.

I am trying to patch Spec.execute so it always takes a screenshot and then have jasmineDone just either save it or not. I previously made this kind of patch, but I no longer work with the company I made the patch for :-(.

I agree that it's nice to be able to put screenshots and reports into folders or naming them. It might be nice to make those as options :) instead of forcing them though.

**Comment by richtera** [comment]
I made a fork of this repo and will make pull request so you can see what I had done before. I just reimplemented it (slightly better than what I had actually)

**Comment by NeverwinterMoon** [comment]
By the way, we didn't have the problem where last screenshot was not working because we were using a rather dirty fix: 

```
afterAll(function(done) {
  process.nextTick(done);
});
```

And rather hoping for Jasmine to have some support for async ops in specDone. No matter how unpleasant the fix is, it is short and it works.

**Comment by richtera** [comment]
It didn't work for me since I needed several loops past to send screenshots to jixee (several completions are involved). My fork uses the promise support in after.

**Comment by bobbyg603** [comment]
Thank you @NeverwinterMoon! I was having the same issue with the last screenshot not working and your solution worked for me.

**Comment by automatictester** [comment]
This doesn't work for me, as per initial comment:

```
This creates a folder for me. and puts the html report in there.
but there are no .png files in the folder.
the report has hyperlinks that go to nowhere.
there are no errors in the console.
```

I don't expect fixes to be delivered in minutes, but this issue was raised in April and we have November now. _Screenshots not being taken_ is a critical problem with core functionality of _protractor-jasmine2-screenshot-reporter_ project.

Is this an abandonware? Do you plan to fix it, or encourage people to use other solutions instead?

**Comment by DanielCaspers** [comment]
I don't know if this will help others, but **I was able to fix my configuration and get it working by moving from protractor 2.5.1 to 3.1.1**

@adamsrobw, perhaps this change is related to Protractor upping their Selenium-Standalone jar version. I was always using the `selenium-server-standalone-jar 2.52.0`, but it sounds like protractor itself was using an older standalone-server according to the [Protractor Changelog](https://github.com/angular/protractor/blob/master/CHANGELOG.md) wasn't in 2.5.1 so there could be a mismatch problem there?

**Other configuration that stayed constant:**
Platform: Windows 7 x64
Framework: Jasmine2
Browser: Chrome
Selenium-Server-Standalone-Jar:  2.52.0
Node: 4.3.1 (note, you must be >= 4.2.x for Protractor 3)
Reporter tool: protractor-jasmine2-screenshot-reporter 0.3.0

**Comment by mlison** [comment]
I've decided not to wait anymore and put the process.nextTick hack to the main repo for now (https://github.com/mlison/protractor-jasmine2-screenshot-reporter/commit/4a00de30dc7174dd654aa956192327e9dbe85f0c) and release it in v0.3.1.

Let's make a new issue if / when needed. Lemme know if there's anything that breaks.

**Comment by martinsson** [comment]
0.3.1 does not solve the problem for me. I've tracked it down to beforeLaunch and thus cleanDestination() not being called. How are these functions supposed to be called? I'd imagine they should be called from the  jasmineStarted hook no?

**Comment by rojosa** [comment]
nothing seems to work, report is generated and when i click on the 'image' in the report, it navigates to the correct path but there's no image and also no images folder.
