### ISSUE TITLE
Possibility to take screenshot at any time (or before "afterEach") and include it to the test report?

### ISSUE THREAD

**Issue by attila123** [mlison/protractor-jasmine2-screenshot-reporter#103]
Thx for this great tool!
The problem we face is that if a spec ("it") fails then the screenshot is not taken immediately after the failure if an "afterEach" is present, but only after the "afterEach" has been executed. The problem with this is that our "afterEach"-s contain cleaning up resources and our GUI reacts to that, which results in a changed screenshot, which is misleading and cannot be used to debug the test failure. We considered tricks like moving the cleanup to "afterAll", but it would be a huge amount of work.
- I am not sure if jasmine allows you to take screenshot (also) after a failed "it", but before "afterEach" is executed, if so, this would be very great!
- If it is not possible (or even if it is possible) it would be very nice if you could add a function which could be called any time to take a screenshot and add it to the report under the currently executing test. (We have a point in our code where we can detect the test errors and could take a screenshot at that point.)

**Comment by mlison** [comment]
To my knowledge, controlling when exactly the screenshot is taken in test's lifecycle is not possible. Jasmine only provides certain hooks that you can bind to and the one that is used - specDone - executes only after other lifecycle methods are finished.

That being said, taking screenshots is actually pretty straight forward and it can be executed at any point in your tests. The trouble here would be with including this into the report. The source for items that end up in the report is currently the list of specs. I'd need to abstract that first and then expose some way how to modify that list explicitly.

Though not impossible, it would take some doing, and I'm afraid I don't have the time right now - I can add it to TODO list, or of course you can also try to implement the feature and open a pull-request (I can at least help answer questions).

**Comment by jmurphy87** [comment]
having the same issue, has anything come out of this?

**Comment by compeek** [comment]
For somewhat of a workaround, you can perform your `afterEach()` work in another browser window/tab so you don't touch your main one where the test failed.

Here's a basic example. Note that I'm using TypeScript with async and await.

```typescript
  afterEach(async () => {
    await browser.executeScript('window.open();');
    await browser.switchTo().window((await browser.getAllWindowHandles())[1]);

    // do stuff

    await browser.close();
    await browser.switchTo().window((await browser.getAllWindowHandles())[0]);
  });
```

**Comment by frankramle** [comment]
Hi, I'm in the same situation
