### ISSUE TITLE
Unnecessary screenshots for missed steps

### ISSUE THREAD

**Issue by rabbitjar** [mlison/protractor-jasmine2-screenshot-reporter#107]
I'm using failFast plugin and when the spec fails, the screenshot reporter continues to generate screenshots for each consecutive spec (even though no specs are executed and all screenshots are exactly the same).
I would like the reporter to stop creating screenshots at the moment the first spec fails.

**Comment by mlison** [comment]
This reporter hooks into jasmine's lifecycle and is triggered when specs finish or fail. I'm not familiar with what fail-fast does, but it looks like it will disable all specs after the first one fails, and then just let the runner run through all of them.
So I think what you are after is the option to [ignore disabled specs](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#ignore-pending-specs-optional).
