### ISSUE TITLE
Is there any way to send protractor html report to email address ?

### ISSUE THREAD

**Issue by AlaKarim** [mlison/protractor-jasmine2-screenshot-reporter#108]
Currently, i am using "protractor-jasmine2-screenshot-reporter" to generate a summary report and create a screenshot but unable to send generated report to any email address. Is there any way exist then please help me out 

Thanks

**Comment by mlison** [comment]
Sorry this is outside of scope of this project.

That being said, the solution to your problem depends on your workflow. If you're, for example, using any task runners like [Gulp](https://gulpjs.com/) you can try plugins like [gulp-email](https://github.com/jansanchez/gulp-email). Or your CI server can probably "publish" build artifacts using an email client. There's plenty different ways how to do this.

In principle, what you're after can be done, but you'll have to do some orchestration around it. You generate the report in one step, and send the email in the next step of the process by whatever means are available to you.

**Comment by AlaKarim** [comment]
Thanks alot
