### ISSUE TITLE
Tests not completed (even with success) on CircleCI

### ISSUE THREAD

**Issue by nicky-lenaers** [mlison/protractor-jasmine2-screenshot-reporter#109]
I fiddled around for days to determine what was causing the following error on CircleCI:

```sh
      - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
          at ontimeout (timers.js:469:11)
          at tryOnTimeout (timers.js:304:5)
```
**This happens even is all tests succeed**. It just hangs after succeeding all tests and then, after the default Jasmine timeout, the error is generated.

I am using the following `protractor.conf.js` file based on Angular CLI basic setup:

```js
/**
 * Protractor configuration file, see link for more information
 *
 * @see https://github.com/angular/protractor/blob/master/lib/config.ts
 */

const { SpecReporter } = require('jasmine-spec-reporter');
const JasmineReporters = require('jasmine-reporters');
const HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

const htmlScreenshotReporter = new HtmlScreenshotReporter({
  dest: './reports/e2e/html',
  filename: 'index.html'
});

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function () { }
  },
  beforeLaunch: function () {
    return new Promise(function (resolve) {
      htmlScreenshotReporter.beforeLaunch(resolve);
    });
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({
      spec: {
        displayStacktrace: true
      }
    }));
    jasmine.getEnv().addReporter(new JasmineReporters.JUnitXmlReporter({
      consolidateAll: false,
      savePath: './reports/e2e',
      filePrefix: '',
      modifyReportFileName: (generatedFileName, suite) => 'test-results'
    }));
    jasmine.getEnv().addReporter(htmlScreenshotReporter);
  },
  afterLaunch: function (exitCode) {
    return new Promise(function (resolve) {
      htmlScreenshotReporter.afterLaunch(resolve.bind(this, exitCode));
    });
  }
};
```

If I comment out this line...

```js
jasmine.getEnv().addReporter(htmlScreenshotReporter);
// becomes
// jasmine.getEnv().addReporter(htmlScreenshotReporter);
```

...the error never occurs. I don't see any error logs from this plugin, but it is somehow preventing the e2e tests on CircleCI to complete. It just hangs.

**Comment by mlison** [comment]
The problem you are describing is actually not related to this project as far as I know.
I've seen this happen all the time in projects that use protractor to run e2e tests even if they don't use this reporter.

That said, I'm afraid I don't have a straight answer for your, there's plenty hacky ways how to circumvent this though :)

**Comment by nicky-lenaers** [comment]
Hi @mlison , thank you for your response. Not to be rude really, but I do find it a little odd that, even though I clearly specified a single variable (in this case, this plugin) causes errors, your answer directs me to "plenty of hacky ways". Isn't there a way to find out *why* this is happening when adding the plugin? And isn't this important to your plugin anyway?

**Comment by mlison** [comment]
> _Not to be rude really, but I do find it a little odd that, even though I clearly specified a single variable (in this case, this plugin) causes errors, your answer directs me to "plenty of hacky ways"_

To be fair, you specified that you have the same problem with this plugin as people have with other protractor plugins. You haven't specified why and how is this caused by this project, nor how to reproduce it.

>_Isn't there a way to find out why this is happening when adding the plugin?_

Certainly, it is likely related to your project setup which makes it difficult for me to debug

>_And isn't this important to your plugin anyway?_

Well sure, not very high in the list though

I closed this mostly because of lack of information - let's reopen when we know more.
