### ISSUE TITLE
When using fit(), no spec is ran

### ISSUE THREAD

**Issue by maxlegault** [mlison/protractor-jasmine2-screenshot-reporter#12]
When using the screenshot reporter, if one or more spec are focused (fit() instead of it()), no spec is ran by Protractor.

However, I am able to run only a focused suite with fdescribe(). But as soon as there is one focused spec, Protractor ends printing "No specs found" in the console.

I am using Protractor 2.0.0 with Jasmine 2.1.1 and protractor-jasmine2-screenshot-reporter 0.1.4.

**Comment by gkohen** [comment]
+1. Our protractor tests can last quite a long time. We need to be able to have the focus and it would be great to use fit again.

**Comment by mlison** [comment]
Closed by #13
