### ISSUE TITLE
have option to save screenshots for failed specs only

### ISSUE THREAD

**Issue by taras80** [mlison/protractor-jasmine2-screenshot-reporter#15]
Please add option that will be saving screenshots for failed specs only.

**Comment by mlison** [comment]
@tkurdyna doesn't opts.captureOnlyFailedSpecs do the trick?
https://github.com/mlison/protractor-jasmine2-screenshot-reporter#capture-only-failed-specs-optional

**Comment by taras80** [comment]
What I meant was to generate html for all specs and take screenshots only for failed specs. Today with  option captureOnlyFailedSpecs being on and all passed specs an empty html report is being generated.
