### ISSUE TITLE
requireJS name incorrect

### ISSUE THREAD

**Issue by kimx** [mlison/protractor-jasmine2-screenshot-reporter#17]
Help says use " require('protractor-jasmine2-screenshot-reporter'); ",but it can't work,after I checked package.json then I adjust "require('protractor-jasmine2-screenshot-report');",I can work.

**Comment by mlison** [comment]
I'm pretty sure the name is protractor-jasmine2-screenshot-report**er**.
The [package](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/package.json#L2) is registered under such name in [npm](https://www.npmjs.com/package/protractor-jasmine2-screenshot-reporter) as well.

**Comment by kimx** [comment]
Oh! sorry~~I saw this package from another author.
https://github.com/asnov/protractor-jasmine2-screenshot-report
