### ISSUE TITLE
Screenshot for last 'it' is not taken

### ISSUE THREAD

**Issue by Priyapanch** [mlison/protractor-jasmine2-screenshot-reporter#18]
For last 'it' the screenshot is not taken:

The below is my config setting
onPrepare: function() {
        jasmine.getEnv().addReporter(new HtmlScreenshotReporter({dest: 'target/screenshots',filename: 'my-report.html'}));
        }

Code sample:
describe('super calculator actions' , function(){

var CalculatorPage = require('./Calc_Page.js');

it('addtion',function(){
    CalculatorPage.navigate();
    CalculatorPage.EnterFirst(3);
    CalculatorPage.SelectOperator("ADDITION");
    CalculatorPage.EnterSecond(4);  
    CalculatorPage.ClickGo();
    var actualVal = element(by.binding('latest')).getText();
    expect(actualVal).toEqual('7');
});
it('verify history',function(){
    var eleHistory = element.all(by.repeater('result in memory'));
    expect(eleHistory.get(0).getText()).toContain('3 + 4 7');

});
});

for last one 'verify history' the screen shot is not taken. any inputs for this?

**Comment by mlison** [comment]
This is actually also related to #4 and to https://github.com/angular/protractor/issues/1938
The problem here is that Jasmine process doesn't wait for all its callbacks to finish.
