### ISSUE TITLE
Problem with screenshot for last step in suite.

### ISSUE THREAD

**Issue by drptbl** [mlison/protractor-jasmine2-screenshot-reporter#20]
Hello,
Everything works fine, I see all steps in HTML report, but when I press on last step (when screenshot should open), it doesn't exist - screenshot for last step in my suite is not saving, no idea why.

Feel free to check it out by running this repo with Protractor:
https://github.com/drptbl/protractortesting/tree/lastscreenshotmissing

I'm talking about this step:
"✓should close cookie frame after acceptation (12 s)" - screenshot is missing.

Any ideas how to fix?
Tried wait and sleep after last step without success.

**Comment by marklagendijk** [comment]
See issue #18. This is a bug in Protractor. You can use the following [workaround](https://github.com/angular/protractor/issues/1938#issuecomment-96276252):

``` javascript
// Hack to force Protractor to wait untill all Jasmine reporters are done.
// See: https://github.com/angular/protractor/issues/1938#issuecomment-96276252
afterAll(function(done){
    process.nextTick(done);
});
```

**Comment by drptbl** [comment]
It worked, thanks!

Issue can be closed now :+1:
