### ISSUE TITLE
Report style format doesn't show summary and table

### ISSUE THREAD

**Issue by blukolladesigns** [mlison/protractor-jasmine2-screenshot-reporter#22]
Hi,

I have the report working however it shows up as a list with the links to the screenshot and not the table and summary at the bottom.  Is there something else i need to do or add to make sure it looks exactly as the examples.  
![screen shot 2015-08-12 at 3 01 31 pm](https://cloud.githubusercontent.com/assets/13770255/9233798/10f25cf2-4103-11e5-8b16-e434bc93ec91.png)

**Comment by premkh9** [comment]
I am also observing the same issue

**Comment by Mani-rpx** [comment]
+1

**Comment by mlison** [comment]
The result summary and links to failed tests were added just now in latest version (0.2.0), could you guys check out if this solves your use cases?
[Display summary in report](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#display-summary-in-report-optional)
[Display configuration summary in report](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#display-configuration-summary-in-report-optional)
[Display links to failed specs in report summary](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#display-links-to-failed-specs-in-report-summary-optional)

**Comment by sukeerthm** [comment]
Result summary is working fine now. But when i am using multicapabilities(with two specs), the result summary should be combination of both the specs. But its showing Report Title , Summary and Config details separately for both the specs. Any help will be much appreciated 

![06-01-2016-11-28-54](https://cloud.githubusercontent.com/assets/15187298/12129463/acc8d70e-b468-11e5-8a7b-4a91333fe20e.png)

**Comment by AndrewFinlay** [comment]
Hi Sukmad, I've tried to solve these problems.  Check out my fork and let me know if you find any issues

**Comment by mlison** [comment]
I think this is resolved already, let's reopen if something is missing.
