### ISSUE TITLE
Report thumbnails image paths and links are broken

### ISSUE THREAD

**Issue by shoaibuddin** [mlison/protractor-jasmine2-screenshot-reporter#30]
Here is my spec:

jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: './reports/e2e/protractor-result',
            screenshotsFolder: '//screenshots'
        }));

**Comment by NicolasRoelandt** [comment]
Same here.

Sometimes, I have links to the screenshot in the html, sometimes not and I have to look for them manually. I have no idea what makes the difference.

**Comment by mlison** [comment]
@shoaibuddin @NicolasRoelandt could you guys try this with latest version of protractor and the reporter and lemme know if this is still a problem? I can't seem to be able to reproduce it.
