### ISSUE TITLE
Howto generate screenshots from multiple browsers?

### ISSUE THREAD

**Issue by mark-veenstra** [mlison/protractor-jasmine2-screenshot-reporter#44]
Is it possible to generate a screenshot from each browser forkedInstance generated in the spec? At this moment I only see one screenshots of the `browser`, but not from the [forked instances](https://angular.github.io/protractor/#/api?view=Protractor.prototype.forkNewDriverInstance).
I have tests that fire up 6 browsers. I need to create screenshots from all of them when the test fails.

**Comment by mark-veenstra** [comment]
Could we somehow get all browsers that have been forked?
I saw in your code that on this line you take the screenhot specifically for the browser: https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/index.js#L420

**Comment by mlison** [comment]
@mark-veenstra I think the problem here is obtaining the reference to a particular fork. You create a fork in your test (local reference), whereas `browser` is a global that can be access from the reporter.

Unless there's a way to access all forked instances of a `browser` I don't see any ease options how to do this.

**Comment by mark-veenstra** [comment]
Hmmm yeah I was also wondering howto get all the browser instances. But how about this for an idea:
1. If you don't configure a variable `myInstances` on the global `protractor` object where your browser instances are, all will be as it is now in your code
2. If you configure a variable `myInstances` on the global `protractor` object it will be used to take all screenshots from these instances

So for example your `index.js` on [L420](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/index.js#L420) changes to something like (not finished the code):

``` javascript
if(protractor.hasOwnProperty('myInstances')) {
  for (key in protractor.myInstances) {
    protractor.myInstances[key].takeScreenshot().then(function (png) {
      // Further adjustments to report all screenshots and add them to the same spec...
      // Maybe also use `key` to the filenaming....
    });
  }
} else {
  browser.takeScreenshot().then(function (png) {
    // As is
  });
}
```

Within the writing of a test someone can add all his forked instances/browsers to the global available `protactor.myInstances` object.

**Comment by mlison** [comment]
closed by https://github.com/mlison/protractor-jasmine2-screenshot-reporter/commit/64405b4df5354703f4aa836fd7302e8e264eecf0 (v0.3.1)

**Comment by mark-veenstra** [comment]
Thnx for the merge and fixes on the code...
