### ISSUE TITLE
cleanDestination set to true is not cleaning destination folder before run

### ISSUE THREAD

**Issue by taras80** [mlison/protractor-jasmine2-screenshot-reporter#45]
When I set cleanDestination to true, I am still seeing reports from previous runs in current run report file.

**Comment by peggybear** [comment]
I'm having the same issue. I have to manually clean out the directory each time, the option `cleanDestination` doesn't make a difference right now in v0.3.0

**Comment by benharold** [comment]
~~+1~~ My mistake. I didn't have my `beforeLaunch` and `afterLaunch` methods setup correctly in my config file.

**Comment by mlison** [comment]
@taras80 @peggybear cleanDestination was actually added in version v0.3.0 and it is enabled by default - did you register your `beforeLaunch` and `afterLaunch` methods? (example [protractor.conf](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/protractor.example.conf))

It seems to behave correctly in my tests.
