### ISSUE TITLE
Adding stacktrace to the HTML report

### ISSUE THREAD

**Issue by mark-veenstra** [mlison/protractor-jasmine2-screenshot-reporter#46]
Is there a reason why the stack trace is not added to the report? I find it handy to have the stack trace available. For example if you have a spec with more expectations than one it it nice to see which line in your file throws the error. This is found in the stack trace.

Maybe the reason template can be expanded to display stack trace onClick, something like:

```
    var reasonsTemplate = _.template(
      '<ul>' +
          '<% _.forEach(reasons, function(reason) { %>' +
              '<li><%- reason.message %> - <a href="toggleDisplay()">Stacktrace</a></li>' +
              '<div id="stacktrace" style="display: none;"><%- reason.stack %></div>' +
          '<% }); %>' +
      '</ul>'
    );
```

**Comment by kummerer94** [comment]
Nice work! Would love to see that included in the project.

**Comment by mlison** [comment]
closed by https://github.com/mlison/protractor-jasmine2-screenshot-reporter/commit/83d46e5adbc292f76079f17b25b424c57770c688 (v0.3.1)
