### ISSUE TITLE
Not getting screenshot when in Ubuntu

### ISSUE THREAD

**Issue by ghost** [mlison/protractor-jasmine2-screenshot-reporter#47]
Hi,

I'm trying out protractor reporting tools and I successfully got a report with screenshots using this when I was in Windows but using the same specs and config files in Ubuntu, I'm only able to get the report with incorrect data and no screenshot was generated.

Could you please advise. Thank you.

**Comment by mlison** [comment]
Could you please be a little bit more specific? Is there any sort of error? Whats your versions and setup?

(tbh I'm a little surprised it worked in Windows in the first place)

**Comment by mlison** [comment]
Let's reopen this when / if this becomes relevant.

**Comment by Vishnu407** [comment]
Same issue here. I am unable to get screen shots in the report when in ubuntu. Need some help.
