### ISSUE TITLE
Is there a way to post the screenshot to AWS?

### ISSUE THREAD

**Issue by moneytree-doug** [mlison/protractor-jasmine2-screenshot-reporter#49]
If I am running tests on CircleCI, then I want it be uploaded to AWS so I can see what the errors were.

**Comment by mlison** [comment]
No, there isn't such feature in the reporter itself. That is something that you usually want to instrument in the build process as another step. For example, after a round of unsuccessful tests you'd trigger the upload using aws-cli tools for example.

**Comment by moneytree-doug** [comment]
@mlison Thank you!
