### ISSUE TITLE
Html Reports with multiple spec files

### ISSUE THREAD

**Issue by sandy-adi** [mlison/protractor-jasmine2-screenshot-reporter#5]
When there are multiple spec files to be run, only the specs from the last spec file are recorded in the html output.

**Comment by mlison** [comment]
Could you please provide some more info? I'd need jasmine version and your spec/suite structure.

**Comment by sandy-adi** [comment]
Here is my spec structure

<pre>
- project_root
| ---Spec
      |---module-one
          |--Spec1.js
          |--Spec2.js
      |---module-two
          |--Spec1.js
          |--Spec2.js
</pre>

I'm using jasmine 2.1.1. So basically after the tests have run, the html output file just has results from one of the files under  `module-two`

I see that you are using fs.writeSync, i'm going to try and use fs.appendSync and see if that addresses the issue.

**Comment by mlison** [comment]
I somehow missed that you can have nested specs in jasmine, try changing your toplevel spec to a describe instead. I assume module-one and module-two are describes already?

**Comment by sandy-adi** [comment]
Oh, this is actually my project directory structure. Module-one and module-two are directories. Each spec*.js file has it's own describe and yes I do have nested describes in some of the specs. The top level in each of the file is a describe.

**Comment by sandy-adi** [comment]
@mlison another thing that I noticed is that you have a dependency on `path` in [package.json L14](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/blob/master/package.json#L14). Path is already built into node, any reason for adding it as a dependency?

**Comment by sandy-adi** [comment]
It appears like when there are multiple test files, the screenshots and the reports are not getting generated consistently.

**Comment by mlison** [comment]
This seems to work with following structure:

<pre><code>- project_root
|---Spec
      |---folder1
          |--test1.js
          |--test2.js
      |---folder2
          |--test3.js
      |---test4.js</code></pre>

Let's reopen this when / if there's more info on the subject.
