### ISSUE TITLE
Screenshot not linked

### ISSUE THREAD

**Issue by kummerer94** [mlison/protractor-jasmine2-screenshot-reporter#51]
I am trying to generate a HTML report with screenshots for my Protractor tests. I am currently testing on two different browsers (Chrome and Firefox).

The plugin will not link the last screenshot but it is present in the directory.

![issues jasmine2-reporter plugin](https://cloud.githubusercontent.com/assets/1760143/13527050/9b41cda2-e20c-11e5-8647-d9acdc96bf97.png)

**Comment by peterklijn** [comment]
A workaround is mentioned here.

https://github.com/mlison/protractor-jasmine2-screenshot-reporter/issues/10#issuecomment-143647225

``` js
...
exports.config = {
  ...
  onPrepare: function() {
    ...
    afterAll(function(done) {
      process.nextTick(done);
    }
  },
  ...
}
```

Tested it and works for me.

**Comment by mlison** [comment]
@kummerer94 yep this is a known bug. It happens because protractor doesn't wait until all reporters are finished before calling `jasmineDone` method which is responsible for writing the final report.
