### ISSUE TITLE
dest directory not created

### ISSUE THREAD

**Issue by martinsson** [mlison/protractor-jasmine2-screenshot-reporter#53]
In the latest version 0.3.1 the issue #10 is not solved for me. As it is a closed issue I'm cross-posting my investigation here.

I've tracked it down to beforeLaunch and thus cleanDestination() not being called. How are these functions supposed to be called? I'd imagine they should be called from the jasmineStarted hook no?

Is this a jasmine misbehavior?

**Comment by mlison** [comment]
Yes and no, jasmine gives you the tools, but you have to register the callbacks yourself _at the moment_. There's an example how to do that in [usage instructions](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#usage).

**Comment by martinsson** [comment]
Thanks, I do not have that option activated though, here's my config

```
var htmlReporterOptions = {
    dest: 'test-results/screenshots',
    filename: 'my-report.html',
    captureOnlyFailedSpecs: true
};
```

I've further tracked it down to failing only when the spec passes

protractor-jasmine2-screenshot-reporter/index.js, function=Jasmine2ScreenShotReporter.jasmineDone, line=499

Here's the "full" stacktrace (somewhat formatted

```
error: uncaughtException: ENOENT, no such file or directory 'test-results/screenshots/my-report.html' date=Mon Apr 18 2016 10:28:18 GMT+0200 (CEST), pid=20494, uid=501, gid=20, cwd=., execPath=/usr/local/Cellar/node012/0.12.7/bin/node, version=v0.12.7, argv=[node, ./node_modules/.bin/protractor, ui-tests/conf.js], rss=135135232, heapTotal=105047552, heapUsed=76253488, loadavg=[2.861328125, 2.876953125, 2.724609375], uptime=571701, trace=[
column=null, file=null, function=Error, line=null, method=null, native=true, column=18, 
file=fs.js, function=Object.fs.openSync, line=500, method=fs.openSync, native=false, column=15, 
file=fs.js, function=Object.fs.writeFileSync, line=1099, method=fs.writeFileSync, native=false, column=6, 
file=fs.js, function=Object.fs.appendFileSync, line=1143, method=fs.appendFileSync, native=false, column=10, 
file=./node_modules/protractor-jasmine2-screenshot-reporter/index.js, function=Jasmine2ScreenShotReporter.jasmineDone, line=499, method=jasmineDone, native=false, column=28, 
file=./node_modules/protractor/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js
```
