### ISSUE TITLE
Can't load external css 

### ISSUE THREAD

**Issue by MihailSeykov** [mlison/protractor-jasmine2-screenshot-reporter#54]
Here is my protractor configuration file :

`var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['spec.js'],
    capabilities: {
        browserName: 'chrome'
    },
    onPrepare: function () {
        jasmine.getEnv().addReporter(new HtmlScreenshotReporter({
            dest: 'target/screenshots_chrome',
            filename: 'my-report.html',
            userCss: 'my-reporter.css'
        }));
        browser.driver.manage().window().maximize();
        jasmineNodeOpts: {
            showColors: true;
            defaultTimeoutInterval: 5000;
        };
        browser.manage().timeouts().pageLoadTimeout(5000);
        browser.manage().timeouts().implicitlyWait(5000);
        allScriptsTimeout: 5000;
        getPageTimeout: 5000;
    },
};`

The problem is that the reporter is not using 'my-reporter.css' in any way. None of the changes i made to the css file are reflected in the report.

**Comment by mlison** [comment]
You config suggests you keep your css file in your css file in your target directory - is that correct?

If its e.g. in your project root you could try using `../my-reporter.css` as the link to the file.

**Comment by MihailSeykov** [comment]
I found what the problem was, thank you for the answer @mlison. The problem was that in my configuration file i did not have beforeLaunch and afterLaunch set correctly. After i did that, my problem was fixed.

**Comment by mlison** [comment]
👍
