### ISSUE TITLE
Found Issue with stack trace in html report. 

### ISSUE THREAD

**Issue by patcyg** [mlison/protractor-jasmine2-screenshot-reporter#56]
**Issue** 
   Clicking on stack trace link opens stack trace details for another spec for other browser. 

**Steps reproducible**
1. Create a test suite with 15 to 20 specs. 
2. Code in such a way that some of specs gets fail each time test suite is executed.  
3. Execute the test suite using  selenium grid environment with different browsers (I have used chrome and firefox browsers ). 
4. After completion of execution, html report will have two section. Let's consider section 1 as firefox section (i.e. it will show testing result executed in firefox) and section 2 as Chrome. 
5. Click on one of the stack trace link in Chrome section. 

**Actual Result**
You will observe that clicking on stack trace link in chrome section will open stack details in firefox section. 

**Sample report**
Attached is the sample report with the same scenario and behavior
[tests-report.html.zip](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/files/225530/tests-report.html.zip)

.

**Comment by mattc41190** [comment]
This is occurring because the two links share the same ID, the method `showhide` receives the same ID and toggles the first one only.

Will look into possible solution.
