### ISSUE TITLE
Report is showing only the last executed test

### ISSUE THREAD

**Issue by guilhotarras** [mlison/protractor-jasmine2-screenshot-reporter#59]
I'm running the reporter on selenium grid, but when my suite ends, the reporter only shows the last executed test.
I also have noticed that I am getting this error on console log, on some tests: "problem trying to remove a folder:./target/reports/desktop/"

Here is my conf : 
var htmlReporter = new HtmlReporter({
    savePath: './target/reports/desktop/',
    filePrefix: 'index.html',
    takeScreenshots: true,
    takeScreenshotsOnlyOnFailures: true,
    captureOnlyFailedSpecs: true,
    cleanDestination: false,
    showSummary: false,
    showConfiguration: false,
    reportTitle: null,
    preserveDirectory: false
});

If I run the tests locally, everything works fine.

Can you help ?
Thanks

**Comment by bebepeng** [comment]
I have the same problem where our reports are only showing the last test file run, but I'm not getting errors logged. We are observing the folder getting replaced after each tests finishes running.
Our config looks like this:

```
var HtmlReporter = require('protractor-jasmine2-html-reporter');

...

onPrepare: function () {
        jasmine.getEnv().addReporter(new HtmlReporter({
            savePath: './_dist/test-reports/',
            cleanDestination: false,
            preserveDirectory: true
        }));
}
```

**Comment by bebepeng** [comment]
@guilhotarras I just realized that you are probably using the html-reporter package (https://www.npmjs.com/package/protractor-jasmine2-html-reporter  , https://github.com/Kenzitron/protractor-jasmine2-html-reporter) instead of the screenshot-reporter .

Screenshot Reporter doesn't use "savePath" as an option, but instead "dest".

**Comment by mlison** [comment]
@bebepeng is correct, this question is unrelated to this repository.
