### ISSUE TITLE
scructure of html is incorrect when using "captureOnlyFailedSpecs"

### ISSUE THREAD

**Issue by butzelbovat** [mlison/protractor-jasmine2-screenshot-reporter#6]
When using the reporter to capture only failed specs, the html structure is incorrect. It first displayes my describe blocks and then, as a new list, the it-blocks of the describe-blocks.

**Comment by mlison** [comment]
@butzelbovat check out v0.1.4 and lemme know how it went. Current structure in the report doesn't reflect spec structure exactly, but there shouldn't be anything missing.

**Comment by butzelbovat** [comment]
fixed! thanks @mlison! Now the report is readable for the team :+1:
