### ISSUE TITLE
Test Report doesn't link the screenshot for the last test

### ISSUE THREAD

**Issue by zgagnon** [mlison/protractor-jasmine2-screenshot-reporter#62]
We have several tests across multiple files, and each screenshot gets appropriately linked except the very last one.

**Comment by mlison** [comment]
I would argue this was solved, at least partially if not completely, by #10. Please upgrade to latest, and take a look on the solutions suggested in the thread - as far as I can tell it works well in my tests.

It could be that this still happens under some specific circumstance - if so, please make a new issue and describe the conditions that lead to the error.

Thanks!
