### ISSUE TITLE
How to get date and time of the run on the html report summary section?

### ISSUE THREAD

**Issue by swetashahi** [mlison/protractor-jasmine2-screenshot-reporter#73]
I want to have a history of runs and would like to see when a test last passed or failed as compared to the latest run.

**Comment by barzik** [comment]
This is the purpose of Jenkin\TraviCI or similiar tools that monitor the build status over the time. I am not sure that this is required or necessary task for Jasmine reporter.

**Comment by mlison** [comment]
@swetashahi, that is not in scope for this project. You can use various continuous integration tools to get a cumulative summary of your test runs / builds - details depend on your project's needs and setup.

**Comment by swetashahi** [comment]
I just need the  getDate() method to print in the title of the report possibly. Just helps to know when a test was run.

**Comment by barzik** [comment]
@mlison If you think this is valid, you can assign it on me.

**Comment by swetashahi** [comment]
I solved it by using the following code in my conf.js file

var today = new Date(),
    timeStamp = today.getMonth() + 1 + '-' + today.getDate() + '-' + today.getFullYear() + '-' + today.getHours() + 'h-' + today.getMinutes() + 'm';

var reporter = new HtmlReporter({
  cleanDestination: false,
  showSummary: true,
  showConfiguration: true,
  showQuickLinks: true,
  reportTitle: "Some title -- Test run on: " + timeStamp,  
  dest: 'target/Reports',
  filename: 'my-report.html',
  pathBuilder: function(currentSpec, suites, browserCapabilities) {
    // will return chrome/your-spec-name.png
    return browserCapabilities.get('browserName') + '/' + currentSpec.fullName;
  }
});

So in the generated HTML report, I get the timestamp along with title. All results are appended in same file so I can maintain a weekly report and archive the file

**Comment by chhayakurani** [comment]
Hi
Can you please write the full conf.js here.
Thanks.

**Comment by kmrajay237** [comment]
let SpecReporter = require('jasmine-spec-reporter').SpecReporter;
var HtmlReporter = require('protractor-beautiful-reporter');
var jasmineReporter = require('jasmine-reporters');
var HTMLReport = require('protractor-html-reporter-2');
var AllureReporter = require('jasmine-allure-reporter');

exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: [
        'specs/Login_SignUp_Logout.js'
        // 'specs/TestSpec.js'
    ],
    restartBrowserBetweenTests: false,
    //Run Only in Chrome Browser
    capabilities: {
        browserName: 'chrome',
        version: '78.0.3904.108',
        platform: 'Any',
        chromeOptions: {
            args: ['--disable-infobars',
                '--w3c=false',
                '--disable-extensions',
                '--verbose'
            ]
        }
    },
    //Run in both chrome and firefox browsers parallelly
    /*multiCapabilities: [
        {
            'browserName': 'chrome',
            'chromeOptions': {
                'args': ['--disable-infobars']
            }
        },
        {
            'browserName': 'firefox',
            'moz:firefoxOptions': {
                'args': ['--safe-mode']
            }
        }
    ],*/

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        isVerbose: true,
        realtimeFailure: true,
        includeStackTrace: true,
    },

    onPrepare: function () {
        browser.ignoreSynchronization = false;
        jasmine.getEnv().addReporter(new SpecReporter({
            displayFailuresSummary: true,
            displayFailuredSpec: true,
            displaySuiteNumber: true,
            displaySpecDuration: true,
        }));

        jasmine.getEnv().addReporter(new HtmlReporter({
            baseDirectory: 'reports/CodeTrac',
            takeScreenShotsOnlyForFailedSpecs: true,
            preserveDirectory: false,
            screenshotsSubfolder: 'images',
            jsonsSubfolder: 'jsons'
        }).getJasmine2Reporter());

        jasmine.getEnv().addReporter(new jasmineReporter.JUnitXmlReporter({
            consolidateAll: true,
            savepath: 'testreport',
            fileprefix: 'xmloutput'
        }));


        var reporter = new AllureReporter({
            allureReport: {
                resultsDir: 'allure-results'
            }
        });
        jasmine.getEnv().addReporter(reporter);

        jasmine.getEnv().topSuite().afterEach({
            fn: function () {
                browser.takeScreenshot().then(function (png) {
                    allure.createAttachment('Screenshot', function () {
                        return new Buffer.from(png, 'base64')
                    }, 'image/png')();
                })
            }
        });
    },

    //HTMLReport called once tests are finished
    onComplete: function () {
        var browserName, browserVersion;
        var capsPromise = browser.getCapabilities();

        capsPromise.then(function (caps) {
            browserName = caps.get('browserName');
            browserVersion = caps.get('version');
            platform = caps.get('platform');

            testConfig = {
                reportTitle: 'CodeTrac Test Execution Report',
                outputPath: './reports/',
                outputFilename: 'CodeTrac',
                screenshotPath: './screenshots',
                testBrowser: browserName,
                browserVersion: browserVersion,
                modifiedSuiteName: false,
                screenshotsOnlyOnFailure: true,
                testPlatform: platform
            };
            new HTMLReport().from('junitresults.xml', testConfig);
        });
    }

};
