### ISSUE TITLE
screenshots aren't reported if browser.restart() is called in test

### ISSUE THREAD

**Issue by fantapop** [mlison/protractor-jasmine2-screenshot-reporter#78]
In my test file, I call browser.restart() so that each test starts with a clean slate.  Unfortunately this is clearing the browser.forkedInstances field that is looped over when determining which screenshots to write.

I reviewed pull request 48 https://github.com/mlison/protractor-jasmine2-screenshot-reporter/pull/48 in which the multi-instance feature was added and I see that these were not originally on the browser object.  Maybe the main browser instance can be left out of forkedInstances array and kept as a default instead?

**Comment by mlison** [comment]
No, I'm afraid not. Once the browser is restarted we loose track of pretty much everything. Moreover, as I mentioned in another issue, this is a limitation on Jasmine's side. specDone is a synchronous command so nothing will wait for it, meaning the browser restarts before any screenshots are taken.
