### ISSUE TITLE
Browser is brought to foreground after each test

### ISSUE THREAD

**Issue by ptarjan** [mlison/protractor-jasmine2-screenshot-reporter#8]
Can the window not be focussed while taking the screenshot? It makes running my tests on my dev-box hard.

**Comment by mlison** [comment]
Yep, I also find it annoying. It seems the webdriver is doing the focusing just before taking the screenshot, but I haven't found any way how to disable it.

**Comment by mlison** [comment]
There is no solution to this selenium-side, as it turns out. Community suggested solutions are to run in a headless browser / virtual machine, or simply spawning a virtual display and bind the test-suite to it.

**Comment by ptarjan** [comment]
Is there a way to run protractor in a headless manner?
