### ISSUE TITLE
Browser Logs

### ISSUE THREAD

**Issue by danielheth** [mlison/protractor-jasmine2-screenshot-reporter#81]
Is there a way to export the browsers debug log and have it linked to from the report as well?

There are often times that i need to see the debug log to know what's going on with a failed test.  The screenshot gets me a long way, but often the log contains more info.

**Comment by mlison** [comment]
Not out of the box, but I think it's not altogether impossible. 

That said, the logs are indeed available to protractor like so:

``` js
browser.manage().logs().get('browser')
```

 You could, for example, use metadatabuilder to fetch them and then include them in spec metadata - though getting them into the report itself might require a bit extra work.

**Comment by azachar** [comment]
Hey @danielheth, 
there is an another plugin https://github.com/azachar/protractor-screenshoter-plugin that makes screenshots snapshots,  logs snapshots any many others. Disclaimer: I am the author of it.

Hope I helped!

Cheers, Andrej
