### ISSUE TITLE
Destination directory to point to a shared location from Mac OS

### ISSUE THREAD

**Issue by alagappanece2007** [mlison/protractor-jasmine2-screenshot-reporter#85]
Is there any way I could provide the Destination directory "dest:" to point to a Shared location from Mac OS. 
If it's of Windows OS, this could be achieved by "\\<Sharedlocation>\". In case of Mac OS, how we could provide a network shared location in dest parameter.

**Comment by mlison** [comment]
That would be outside of this project's scope. I suggest using some task runner to do this. E.g. if you're already running your tests using [gulp](https://github.com/gulpjs/gulp), you can just add a task to copy the resulting screenshots to your required destination.
