### ISSUE TITLE
Add process.on to beforeLaunch

### ISSUE THREAD

**Issue by jrm06c** [mlison/protractor-jasmine2-screenshot-reporter#86]
Just letting people know as an FYI...

The report doesn't get any data and isn't closed out if protractor/webdriver hits an uncaughtException.

Add this to the beforeLaunch function in the protractor config file to account for uncaughtExceptions:

process.on('uncaughtException', function () {
            reporter.jasmineDone();
            reporter.afterLaunch();
});

**Comment by mlison** [comment]
Thanks, thats a good info. I've added this to readme.
