### ISSUE TITLE
Is it possible to disable taking screenshots?

### ISSUE THREAD

**Issue by Ukochka** [mlison/protractor-jasmine2-screenshot-reporter#87]
Hi, I have some issue with taking screenshots, but I really like HTML report. Is it possible to keep only html report without screenshots?

**Comment by mlison** [comment]
Hi,

no, I'm afraid that is not possible in with this package. The purpose of this one is mainly to take screenshots.
There's plenty other projects that do HTML-only reports well, though. Check out these for example:
https://github.com/taras42/karma-jasmine-html-reporter
https://github.com/dtabuenc/karma-html-reporter
