### ISSUE TITLE
How to pass options to screenshot function call?

### ISSUE THREAD

**Issue by monkpit** [mlison/protractor-jasmine2-screenshot-reporter#98]
I'm trying to use this tool with the new '--headless' option in the latest Chrome Canary build. When I generate screenshots they are all empty, and it appears to be related to this issue: https://github.com/schnerd/chrome-headless-screenshots/issues/1

The solution to the issue is to pass {fromSurface: true}. Is it possible to pass this option in the reporter so that my screenshots are not blank?

**Comment by mlison** [comment]
- Did you actually try if this works? I read in the documentation that this option defaults to true so in theory there shouldn't be a need to pass it.
- How does it affect the capture if you run it without --headless option?

**Comment by benc** [comment]
I also had blank screenshots, but it worked when I switched to node 8.

**Comment by monkpit** [comment]
This was also fixed for me by updating to node 8. Not sure why it works, but thanks for the tip!

**Comment by neilthawani** [comment]
Unable to get this to work, even using Node 8.
