### ISSUE TITLE
dynamic destination folders

### ISSUE THREAD

**Issue by Harish247** [mlison/protractor-jasmine2-screenshot-reporter#99]
Can we load the files into different destinations?
For Example, I am running tests on some URL: **https://abs.com**.
and I want to save the result in **target/abs/** how can we do this?

I am trying to get the browser.baseUrl but we are defining reporter before browser launch. so, it is not possible.

Any Suggestions?

**Comment by mlison** [comment]
In theory this may be somehow possible if you use custom [pathBuilder](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#path-builder-optional) method.

You will most likely need to implement all the necessary details (directory creation, file naming, etc), but I think it could work.

**Comment by Harish247** [comment]
Thanks for the solution.
